StatisticEI/Models/ConfigModel.cs
using System.Collections.Generic;

namespace StatisticEI.Models
{
    internal class ConfigModel
    {
        public string QldvConn { get; set; }
        public List<string> DataConns { get; set; }
    }
}

StatisticEI/Models/DbInfo.cs
namespace StatisticEI.Models
{
    public class DbInfo
    {
        public string Id { get; set; } = null!;
        public string IP { get; set; } = null!;
        public string Name { get; set; } = null!;
        public string ConnectionString { get; set; } = null!;

        public DbInfo(string connectionString)
        {
            var info = connectionString.Split(";");
            foreach (var item in info)
            {
                if (item.Contains("Data Source"))
                {
                    IP = item.Split("=")[1].Replace(",1433", "");
                }
                else if (item.Contains("initial catalog"))
                {
                    Name = item.Split("=")[1];
                }
            }
            Id = IP + "_" + Name;
            ConnectionString = connectionString;
        }
    }
}

StatisticEI/Models/DbStatistic.cs
namespace StatisticEI.Models
{
    public class DbStatistic
    {
        public string DbId { get; set; } = null!;
        public List<InvoiceBase>? SignedInv { get; set; }
        public int? SignedInvCount { get; set; }
        public int? TCTSuccessInvCount { get; set; }
        public int? TCTProcessInvCount { get; set; }
        public int? TCTErrorInvCount { get; set; }
        public int? ErrorInvCount { get; set; }
        public string? Note { get; set; }
        public bool HasError { get; set; }
    }
}

StatisticEI/Models/ErrorViewModel.cs
namespace StatisticEI.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StatisticEI/Models/InvStatisticResult.cs
namespace StatisticEI.Models
{
    public class InvStatisticResult
    {
        public List<DbStatistic>? DbStatistics { get; set; }
    }
}

StatisticEI/Models/InvoiceBase.cs
using StatisticEI.Enums;

namespace StatisticEI.Models
{
    public class InvoiceBase
    {
        public int Id { get; set; }
        public DateTime ArisingDate { get; set; }
        public int ComID { get; set; }
        public DateTime ModifiedDate { get; set; }
        public decimal No { get; set; }
        public string Pattern { get; set; } = null!;
        public DateTime PublishDate { get; set; }
        public string Serial { get; set; } = null!;
        public InvoiceStatus Status { get; set; }
        public int? TCTCheckStatus { get; set; }
    }
}

StatisticEI/ViewModels/InvStatisticViewModel.cs
using StatisticEI.Models;

namespace StatisticEI.ViewModels
{
    public class InvStatisticViewModel
    {
        public DateTime StatisticDate { get; set; }
        public List<DbInfo> Dbs { get; set; } = new List<DbInfo>();
        public InvStatisticResult? StatisticResult { get; set; }
    }
}

StatisticEI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StatisticEI.Models;
using System.Diagnostics;

namespace StatisticEI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StatisticEI/Controllers/InvStatisticController.cs
using Microsoft.AspNetCore.Mvc;
using StatisticEI.Services;
using StatisticEI.ViewModels;
using System.Globalization;

namespace StatisticEI.Controllers
{
    public class InvStatisticController : Controller
    {
        private readonly InvStatisticService _invStatisticService;
        public InvStatisticController(InvStatisticService invoiceService)
        {
            _invStatisticService = invoiceService;
        }
        public IActionResult Index(string date)
        {
            DateTime statisticDate = string.IsNullOrEmpty(date) ? DateTime.Now.AddDays(-1) : DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            var vm = new InvStatisticViewModel()
            {
                StatisticDate = statisticDate,
                StatisticResult = _invStatisticService.GetStatistic(statisticDate)
            };
            return View("/Views/InvStatistic/Index.cshtml", vm);
        }

        public IActionResult Statistic(string date)
        {
            DateTime statisticDate = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            _invStatisticService.Statistic(statisticDate);
            return Index(date);
        }

        public IActionResult ExportErrorInvoice(string date)
        {
            DateTime statisticDate = DateTime.ParseExact(date, "dd/MM/yyyy", CultureInfo.InvariantCulture);
            var stream = _invStatisticService.ExportErrorInvoice(statisticDate);
            return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "invoice_statistic_" + statisticDate + ".xlsx");
        }
    }
}

StatisticEI/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StatisticEI/Views/InvStatistic/Index.cshtml
@using StatisticEI.ViewModels

@model InvStatisticViewModel
@{
    ViewData["Title"] = "Invoice";
}
@section Style {
    <link rel="stylesheet" href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.css" />
}
<form method="post" action="">
    <div class="my-2">
        <div class="mb-3 row">
            <label for="staticEmail" class="col-sm-2 col-form-label">Ngày</label>
            <div class="col-sm-3">
                <input class="form-control" id="statistic-date" name="date" value="@Model.StatisticDate.ToString("dd/MM/yyyy")" />
            </div>
        </div>
        @*Cập nhât từ: <strong>@(Model.StatisticDate.ToString("yyyy-MM-dd HH:mm:ss"))</strong>*@
    </div>
    <table class="table table-bordered">
        <thead class="table-dark">
            <tr>
                <th scope="col">DB</th>
                <th scope="col">Đã ký</th>
                <th scope="col">Hợp lệ</th>
                <th scope="col">Không hợp lệ</th>
                <th scope="col">Đang kiểm tra</th>
                <th scope="col">Lỗi</th>
                <th scope="col">Ghi chú</th>
            </tr>
        </thead>
        <tbody>
            @if ((!Model.StatisticResult?.DbStatistics?.Any()) ?? true)
            {
                <tr>
                    <td colspan="5" class="text-center">Chưa có kết quả thống kê</td>
                </tr>
            }
            else
            {
                foreach (var item in Model.StatisticResult!.DbStatistics!)
                {
                    <tr>
                        <td>@Html.Raw(item.HasError ? $"<span class='badge bg-danger'>{item.DbId}</span>" : item.DbId)</td>
                        <td>@item.SignedInvCount</td>
                        <td>@item.TCTSuccessInvCount</td>
                        <td>@item.TCTErrorInvCount</td>
                        <td>@Html.Raw(item.TCTProcessInvCount > 0 ? $"<span class='badge bg-danger'>{item.TCTProcessInvCount}</span>" : "0")</td>
                        <td>@Html.Raw(item.ErrorInvCount > 0 ? $"<span class='badge bg-danger'>{item.ErrorInvCount}</span>" : "0")</td>
                        <td>@item.Note</td>
                    </tr>
                }
            }
        </tbody>
    </table>
    <div>
        @if (Model.StatisticResult?.DbStatistics?.Sum(s => s.TCTErrorInvCount) > 0)
        {
            <button type="button" id="rescan" class="btn btn-primary me-2">Thống kê lại</button>
        }
        <button type="button" id="export" class="btn btn-primary me-2">Xuất hóa đơn lỗi</button>
    </div>
</form>
@section Scripts {
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script type="text/javascript">
        $("#statistic-date").datepicker({
            format: 'dd/mm/yyyy',
            autoclose: true
        });
        $("#statistic-date").on('change', function () {
            $('form').attr('action', '/InvStatistic/Index');
            $('form').submit();
        });
        $("#rescan").on('click', function () {
            $('form').attr('action', '/InvStatistic/Statistic');
            $('form').submit();
        });
        $("#export").on('click', function () {
            $('form').attr('action', '/InvStatistic/ExportErrorInvoice');
            $('form').submit();
        });
    </script>
}

StatisticEI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StatisticEI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StatisticEI.styles.css" asp-append-version="true" />
    @await RenderSectionAsync("Style", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StatisticEI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InvStatistic" asp-action="Index">Invoice</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - StatisticEI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>